project:
  type: website

website:
  title: "carviagu"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Courses

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true