project:
  type: website
  output-dir: docs

website:
  title: "Carviagu Site"
  page-footer: 
    left: 2023 Carviagu. Powered with [Quarto](https://quarto.org/) and [GitHub](https://pages.github.com/)
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/carviagu/
        aria-label: LinkedIn Profile
      - icon: github
        href: https://github.com/carviagu
        aria-label: Github Repositories
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: courses.qmd
        text: Courses
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/carviagu/
        aria-label: LinkedIn Profile
      - icon: github
        href: https://github.com/carviagu
        aria-label: Github Repositories
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  